[package]
name = "crab-can"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
nix = { version = "0.27.1", features = ["sched", "process", "fs", "hostname", "mount"]}
anyhow = "1.0"

